server:
  contextPath:

jwt:
  header: Authorization
  secret: s3cret
  expiration: 604800

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework:
      security: DEBUG