server:
  contextPath: /api

jwt:
  header: Authorization
  secret: s3cret
  expiration: 604800

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
      url: jdbc:postgresql://0.0.0.0:5432/test
      username: test
      password: test
      driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework:
      security: DEBUG