version: "3"

services:

  server:
    image: kbhit/project:1.0-SNAPSHOT
    ports:
      - 8080:8080

  database:
    image: postgres:9.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  swaggerui:
    image: swaggerapi/swagger-ui:v3.0.5
    ports:
      - 9999:8080